pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
            }
        }

        stage('Build') {
            steps {
                dir('Backend') {
                    bat '''
                        gradlew.bat clean build -x test
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                dir('Backend') {
                    bat '''
                        gradlew.bat test --stacktrace --info
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'BUILD SUCCESSFUL'
        }

        failure {
            echo 'BUILD FAILED'
        }
    }
}