pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
            }
        }

        stage('Build') {
            steps {
                dir('Backend') {
                    bat 'gradlew.bat clean build -x test'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Backend') {
                    withCredentials([
                        string(
                            credentialsId: 'postgres-test-password',
                            variable: 'TEST_DB_PASSWORD'
                        )
                    ]) {
                        bat '''
                            set SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5433/RealApp
                            set SPRING_DATASOURCE_USERNAME=postgres
                            set SPRING_DATASOURCE_PASSWORD=%TEST_DB_PASSWORD%
                            set SPRING_DATA_REDIS_HOST=127.0.0.1
                            set SPRING_DATA_REDIS_PORT=6380

                            gradlew.bat test --stacktrace
                        '''
                    }
                }
            }
        }

        stage('Docker Check') {
            steps {
                bat 'docker version'
            }
        }
    }

    post {
        success {
            echo 'BUILD SUCCESSFUL'
        }

        failure {
            echo 'BUILD FAILED'
        }
    }
}