spring.application.name=RealTime

#spring.datasource.url=jdbc:postgresql://localhost:5432/RealApp
spring.datasource.url=${SPRING_DATASOURCE_URL}

#spring.datasource.username=postgres
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}

#spring.datasource.password=s17
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true


#spring.data.redis.host=localhost
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}

#spring.data.redis.port=6379
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG


//realtime api key

#
##groq.model=llama-3.3-70b-versatile


spring.ai.openai.api-key=${AI_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=openai/gpt-oss-20b



spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none

spring.ai.model.image=none
spring.ai.model.embedding=none
spring.ai.model.moderation=none
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never